version: '3'
# '2' - focus: single-node dev/test
# '3' - focus: multi-node orchestration
# If not using swarm or kubernetes stick to v2

services:

  webapp-sample:
    container_name: webapp-sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=__your-secret-goes-here__

# To run:
# docker-compose -f docker-compose.yml up -d --build
# If works to destroy:
# eval $(docker-machine env -u)
# docker-machine rm sample
# To clear everything
# docker system prune -a
